### ISSUE TITLE
Версия FormLister

### ISSUE THREAD

**Issue by Aharito** [Pathologic/Comments#1]
> Установить FormLister версии 1.9.0 или выше.

Имеется в виду - 1.8.0 или выше?

**Comment by Pathologic** [comment]
Нет, 1.9.0 и выше.

**Comment by Aharito** [comment]
> Нет, 1.9.0 и выше.

Что-то я не увидел таких версий здесь у вас.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/FormLister/blob/develop/assets/snippets/FormLister/docs/history.md - а это что?
